POST http://localhost:3001/api/auth
Content-Type: application/json

{
    "username": "cory",
    "password": "testpassword2"
}

###

GET http://localhost:3001/api/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNvcnkiLCJpZCI6NSwiaWF0IjoxNjYzMzI4NjkzfQ.7agTSy5qlMdp0eWXw_6_sIVo_qSE1Tq49baFDg1oUmA

