const coins = ['ETHUSDT', 'BTCUSDT', 'SOLUSDT', 'NEARUSDT', 'AVAXUSDT', 'HNTUSDT', 'RLCUSDT', 'LINKUSDT', 'XRPUSDT', 'AAVEUSDT', 'DOGEUSDT', 'CHZUSDT', 'MATICUSDT', 'EOSUSDT', 'ADAUSDT', 'APEUSDT', 'LTCUSDT',
'ATOMUSDT', 'DOTUSDT', 'GMTUSDT', 'CRVUSDT', 'COTIUSDT', 'TRBUSDT', 'KNCUSDT', 'AXSUSDT', 'ENSUSDT', 'FILUSDT', 'MANAUSDT', 'WAVESUSDT', 'UNFIUSDT', 'FTMUSDT', 'DYDXUSDT', 'RUNEUSDT', 'ICPUSDT' ]


module.exports = {apiKey, secret, coins}

